/**
 * Known-v2 content fingerprints — GENERATED FILE, do not edit by hand.
 *
 * Regenerate with:
 *   RUBBER_DUCKY_LEGACY=/path/to/rubber-ducky-legacy bun scripts/generate-v2-fingerprints.ts
 *
 * v2 shipped skills, agents, examples, references, Obsidian config, and
 * settings directly into vaults with no manifest. The adopt verb uses these
 * sha256 hashes to claim byte-identical v2-shipped files (refresh or remove
 * them) while treating anything unrecognized as user-owned or hand-modified.
 *
 * Coverage: file-based assets are hashed across the legacy repo's full git
 * history; generated content is hashed from the legacy HEAD generators only.
 * A v2 file from an intermediate release whose generated bytes differ will
 * surface as a conflict (explicit prompt / --force) instead of matching —
 * the failure mode is always "ask", never "silently overwrite".
 */

/** sha256 hashes of every known v2-shipped skill/agent/example file. */
export const V2_ASSET_HASHES: ReadonlySet<string> = new Set([
  "01a0071222670242b769fd9fc1ad08d7cc98245a49577a63d715d227852af261",
  "0b644ef24e24828e4bea41246dce653748607dbfac086793212d5cdb211ad3c0",
  "0b8da15184e6d73c83e7d18ecec76931d2239eff916399da76de70ec5d3b202a",
  "0bc45def1ccff8be9c2aae5a42b1d04c16521cde00352f85e65a8be738381128",
  "0e81f0cfd3b6a216996f6890d761250d5f90e90a7a78e9c0a322687d49ec275c",
  "0e9d2f3220829cee01af5aac9b0945af4373df83bb0c15a8abb05d1bfaa66165",
  "172d6e87fb98d627c3df6ca90ec09d7c262b1a0d43fd13f3cf813a0f75b5c3ba",
  "19970dfd792e0c1a957d7d8c70bab056a9b4bda20bcde511da4613217f414c07",
  "24004005d66ba5d6dbac556dca18e08b3033fe46d9cf557ac6963d089b6545ad",
  "2d35273d7009d02ac85f43d7714b53b3ae053c6cd49c16289b5517118372a3dc",
  "39d18606621d7ad3fb46b4cf41f77459ea0f724e371a2795e94bf4fd1d58cc3f",
  "42bd423f95f5b84883d91139bdd9df78376375207019cbb756196afab584e87a",
  "44b94ce896352e447ad6c57c5f6e86e8ddf4b3699eda38356d964c9be4914141",
  "489cdf7ad8cf911ea125c7ceba866eb48bcd2dc9e50c0711bf88d45fe1f5c1ee",
  "55c124bdbaa910a350937f538668e94254ac1c58406f207d7a9782135f54bce8",
  "5c29b75f2196e892a34c2249386486edb3e51ebc826409b31aa5af5beeca478f",
  "5c6fb5aaff71129b2ec69a24dedfc4e87c32cd3ea802a8dac7cc4a13c6aefde2",
  "64af1f5fa28eab57d6fea046e87cae7529650facc6f8bc33e187856b19d0331b",
  "6a3e1bf5ef9ac3ccc402a803ca423e9dd44b6d7d0464b5f11759a84553cbdc26",
  "6bdd6bcb6e2ca17059e5ff196fa294ef794366a1bd242f9036e8bda9f8504778",
  "6e81379a99a4bcc83c020ed41a720b5903994362812990489ac7331005acd4ee",
  "72f1679c78a7d66e625a15d2d8788462fe8bfc02c8b3368263454ab0b4f22939",
  "740db40da259564ae371df891cbe9a382b0173da814ca1d2ceb3b18a8f8a59a4",
  "77089c70a736925ce1dae88228596c400122a15ddfa652f29db76d085ad64747",
  "783fbb3cba1d83ebc37950302e1291b0afd0567950a289951f2c23352a007367",
  "7a0e7c35263c251935bd2f34e4880899b51584041995c01290fc1245e7b54a04",
  "7ee3b1d217b2b16e83a26b87db457e2eae043eba46b43b31b334e1c758c7b461",
  "8128ffaf66c27caa3c2214d166e6abe87c0424b6e3b59b7ef6c82a2796d2c0e5",
  "8626d59326004d707dcdc0855c51081b92cb5d91c1a075faec191257e368d9ec",
  "869407eb877740f24869a78eca7cfe58024771aca944990097cfd04f3906e230",
  "8771481ae2ea8dcd361c73af761d710cfb426eb357a1c93d7351c65d99ba2103",
  "9070d031cadca0132fc95d773fd5abc25eabaf0d42136d1345eaac72d3b9191e",
  "90e0b48dc2272c32d4904340328647debf24866c54d3bdb3d0672c25f607dce4",
  "914fa9c264ba15753292b57decec8d2b081638bea7273f1ab84129561e652803",
  "9448199a700f4321a09b45fb082d0082bb1f6f4dc419a484813286364c8b0310",
  "a48474ca5710de3ee734884fb7bb65612406b00be5352679fcf7c4c3c52c1827",
  "aaa1a6df1c59cd657f7ab3591cc7083d189a7a12fda2636f6cc580a55cefbae1",
  "b3f256b172b62842d9648eec1b8cc7a5d3c2441bd9dd73d4e7a7a29a5b05e81f",
  "b4cccb0278e81961692a9b18b57507ba1bb2cc8f86e5756aa5400c6a8597313b",
  "b8c202f5b5aa863a46dcbac51f569b162c31c26638b82d108dd9fd27bc7a3980",
  "bf01f77d42c59eda7a506b07ecd09f931988de2fb66775f5897eda6a9c41bbaa",
  "c14e56321777d03724d6ea02da9dd484001f18a2fc7acdba7c192477fdc055ab",
  "c1d5080bc2a962b22d94e9207410fdcd8030a202ad1b753d7daa4eb9c5e8615a",
  "c33f4ef1cdf548d298a634ff716695ff5c52859fa5c1709c9d74836543043d1f",
  "c6ef954c8535d65ec8ff808d1cff0a5a37c5ebdea9d49091c5bb0b789a8572ce",
  "cefb80b51e75cfe1a35c15776f2d8c0d38ad4900485fd55f39cc425348ce3b79",
  "d102a49eb827e35cc52cdc397d2626e27711e17b3e18db23689df6e6a95d8383",
  "d1eeca85c2e9d165123434d30458421ed485eaa14cc59838c397f500cd03b243",
  "d98801a69cccab2006c783a3b731bc91995683976e2cd57049104aa79943daf9",
  "da7460d16878be01ba89afee2cfa988324e5b6f29c39e7ff055c6af88a196b54",
  "df03f6d6ed81746c2eb2662ecc7cee90261eff0f6880da17b8bf2a22333b36e5",
  "e614fae4c8c20b5aa4f1fe4cc834a33387f3c6d2e1b8e62eddb5b087a6635202",
  "e647521a49bce6b5988b8e31b5efb5ec3a2d355bd0a5054f05f20ab61159fbb1",
  "ea69df11176632015442fdaff3dd26bc81f0b54d7ca8ac3af10f23a742eeff4b",
  "ecfffd3d4f33bfd966743f22fbcbea1e4847d3975fca8fb568bb7be97f4499ee",
  "f003c770a37e69b2ab8690b10a2f1fd9cf162752b0a7509bbdecd43e0df7e4e8",
  "f65d9b5d605881fd5bc0e435c7e890b1d01dcad37d5a8fd048c97876dd270ec7",
  "f82f3ca0f664a7140b9e2e103f74d41f3ff57c22d3efae01f88a5e42582855d6",
  "fd370eabee294740a5cb19736acc03e0af43a41d386c53f4b51d42ab0250b47e",
  "fdc424463081d41f150e2d5b104fa06f3ddfd2488e3c55199ada8abdfc1e4a78",
]);

/** Skill directory names v2 ever shipped under `.claude/skills/`. */
export const V2_SKILL_DIRS: ReadonlySet<string> = new Set([
  "add-data-source",
  "asap",
  "asap-process",
  "close",
  "code-review",
  "comment",
  "connect",
  "good-morning",
  "grill-me",
  "help",
  "ingest-github",
  "ingest-writing",
  "link",
  "lint",
  "meeting-note",
  "new-ticket",
  "onboard",
  "pull-active",
  "push",
  "query",
  "reconcile",
  "release",
  "remind",
  "start",
  "start-project",
  "transition",
  "triage",
  "ubiquitous-language",
  "weekly-summary",
  "wrap-up",
]);

/**
 * sha256 hashes of the constant tail of a v2-generated CLAUDE.md (everything
 * after the first `# <name>` line, which is the only name-parameterized
 * part of a silent-init v2 CLAUDE.md).
 */
export const V2_CLAUDE_MD_TAIL_HASHES: ReadonlySet<string> = new Set([
  "f39e42063ffb16f4bd1416aa51ec3e2135e366078a711fd06f0f7ef5dec01961",
]);

/** Path-keyed sha256 hashes of v2-generated files (settings, references, context pages, Obsidian config). */
export const V2_FILE_HASHES: ReadonlyMap<string, readonly string[]> = new Map([
  [".claude/settings.json", [
    "d244b86a30b0a457024e1a85bf23dbe255f8005c5a13678baac8522832c7e719",
  ]],
  [".gitignore", [
    "bbc6ef9a562583cd005fd20538442ec695203b4f318dd6b787df8eeb5715e51c",
  ]],
  [".obsidian/community-plugins.json", [
    "9c3124cc6ef340fe659dcaf6fd5651aa41fdadae72d2d877ffed595fd949ecde",
  ]],
  [".obsidian/plugins/dataview/data.json", [
    "704e9d214e02b3c5ee86b723329fc7b47c0bd284db807690faffb60380abaf1b",
  ]],
  ["references/frontmatter-templates.md", [
    "cd3f942e91b12fb88ef8f528a0cd4ea346dcfa0c96e4543a7698eaad4f0596a7",
  ]],
  ["references/when-to-use-cli.md", [
    "2b83d6ee0b7568971cd510bf0c701bfd31cd9fa3efd5656cd3eee1d19c1ada32",
  ]],
  ["settings.json", [
    "c061e36d714074fe6f54c9f9c65084f39796d46a46e435911b60e9205da04d0d",
  ]],
  ["wiki/about.md", [
    "9e0e4755708498255efa902830d574c3f185bb45ee940e257fcf424603dc8074",
  ]],
  ["wiki/preferences.md", [
    "419cfa29c93182f02fdc169bb81871594d149586fb4c2c733c0e06eaa9152ddf",
  ]],
  ["wiki/vocabulary.md", [
    "1ecb1818793a8e11884b2ef7d7ced1d6aa6717b864f2ce56cbc2f2ac96fa1895",
  ]],
  ["wiki/voice.md", [
    "0faee4e651f61c1e6948a3839e55b28db8cde2939e7149b465d9362faf9cda1e",
  ]],
]);
